/* Generated by Together */

/**
 * For a description of Permanent visitors, follow hyperlink to the Administration use case
 * for issuing a new Permanent visitor permit.
 */
public class Permanent_visitor_permit extends Permit {
	
	public Permanent_visitor_permit(String permitHolder) {
		super(permitHolder);

    }
	
	public String toString() {
		String s = "Type: Permanent Visitor Permit, name: " + this.getName() + "; #entries:" + this.getEntries() + "; warnings: " + this.getWarnings() 
				+ ". Suspended? " + this.isSuspended() + ". Vehicle used today: " + this.getVehicleUsedToday().getRegNo() + ". Number of permitted vehicles:"
				+ this.getVList().getSize();
		return s;
	}
}


