/* Generated by Together */

/**
 * For a description of Permanent visitors, follow hyperlink to the Administration use case
 * for issuing a new Permanent visitor permit.
 */
public class Permanent_visitor_permit extends Permit {
	
	/**
  	 * Permamemt_visitor_permit Constructor
  	 */
	public Permanent_visitor_permit(String permitHolder) {
		super(permitHolder);
    }
}


