import java.time.LocalDate;

/* Generated by Together */

/**
 * For a description of Regular visitors, follow hyperlink to the Administration
 * use case for issuing a new Regular visitor permit.
 */
public class Regular_visitor_permit extends Permit {
	/**
	 * The name of the University member hosting the visit.
	 */
	private String hostName;

	/**
	 * The date that the visit starts - entry will not be allowed before this date.
	 * 
	 * @label Starting on
	 * @clientCardinality 1
	 * @supplierCardinality 1
	 * @link aggregation
	 * @directed
	 */
	private Date lnkDate;

	/**
	 * The date that the visit ends - entry will not be allowed after this date.
	 * 
	 * @label Ending on
	 * @clientCardinality 1
	 * @supplierCardinality 1
	 * @link aggregation
	 * @directed
	 */
	private Date lnkDate1;

	/**
	 * This requires the name of the University member receiving the visitor, the
	 * name of the visitor (the permit holder), the visitor's vehicle registration
	 * numbers and the start and end dates on which the visits will occur. This
	 * category of visitor would be appropriate for, say, a researcher collaborating
	 * with someone in the University for a couple of weeks, or for actors appearing
	 * in a short-running production at the MacRobert Theatre. 
	 **/
	public Regular_visitor_permit(String permitHolder, Date startDate, Date endDate, String hostName) {
		// super( permitHolder, noOfEntries, warnings, suspended, enteredToday,
		// vehicleUsedToday, permittedVehicles);
		super(permitHolder);
		this.lnkDate = startDate;
		this.lnkDate1 = endDate;
		this.hostName = hostName;
	}

	/**
	 * Get the string with the information of a Permit
	 */
	public String status() {
		String s = "Permit type: Regular Visitor Permit \n" + super.status() 
				+ "Hosted by: " + hostName + "between day #" + lnkDate.getDay() + " and day #" + lnkDate1.getDay();
		
		return s;
	}
	
	public void changeHostName(String s) {
		hostName = s;
	}

	public String getHostName() {
		return hostName;
	}

	public Date getStartDate() {
		return lnkDate;
	}

	public void changeStartDate(Date d) {
		lnkDate = d;
	}

	public Date getEndDate() {
		return lnkDate1;
	}

	public void changeEndDate(Date d) {
		lnkDate1 = d;
	}
	
	public boolean isExpired(Date today) { return  today.getDay() > lnkDate1.getDay();}
	
	public boolean isAllowed(Vehicle_info v, Date d) {
    	if(!super.isAllowed(v, d))
    		return false;
    	if ((d.isEqual(lnkDate) || d.isAfter(lnkDate)) && (d.isEqual(lnkDate1) || d.isBefore(lnkDate1)))
    		return true;
    	return false;
    }
	
	public String toString() {
		String s = "Type: Regular Visitor Permit, name: " + this.getName() + "Permit valid between day #"
				+ lnkDate + " and day #" + lnkDate1 + ". Hosted by: " + hostName + "; #entries:"
				+ this.getEntries() + "; warnings: " + this.getWarnings() + ". Suspended? " + this.isSuspended()
				+ ". Vehicle used today: " + this.getVehicleUsedToday().getRegNo() + ". Number of permitted vehicles:"
				+ this.getVList().getSize();
		return s;
	}
}
