/* Generated by Together */

/**
 * For a description of University member permits, follow hyperlink to the Administration
 * use case for issuing a new University member permit.
 */
public class University_member_permit extends Permit {
    /**
     * The date that this permit was issued. This information is required in case a member
     * of the University leaves the University part way through the year and becomes eligible for a pro-rata rebate.
     * @label Issued on
     * @clientCardinality 1
     * @supplierCardinality 1
     * @link aggregation
     * @directed
     */
    private Date lnkDate;
    
    public University_member_permit(String permitHolder, Date lnkDate) {
    	super( permitHolder);
    	this.lnkDate = lnkDate;
    }
    
    
    /**
	 * Get the string with the information of a Permit
	 */
	public String status() {
		String s = "Permit type: University Member Permit \n" + super.status() 
				+  "Date of issue: #" + lnkDate.getDay();
		
		return s;
	}
    
    public void changeDate(Date d) {
    	lnkDate = d;
    }
    
    public Date getIssueDate() {
    	return lnkDate;
    }
}
