/* Generated by Together */

/**
 * For a description of University member permits, follow hyperlink to the Administration
 * use case for issuing a new University member permit.
 */
public class University_member_permit extends Permit {
    /**
     * The date that this permit was issued. This information is required in case a member
     * of the University leaves the University part way through the year and becomes eligible for a pro-rata rebate.
     * @label Issued on
     * @clientCardinality 1
     * @supplierCardinality 1
     * @link aggregation
     * @directed
     */
    private Date lnkDate;
    
    /**
     * Constructor
     * 
     * @param permitHolder the permit holder name
     * @param lnkDate 	   the issue date
     */
    public University_member_permit(String permitHolder, Date lnkDate) {
    	super( permitHolder);
    	this.lnkDate = lnkDate;
    }
    
    /**
	 * Get the string with the information of a Permit
	 */
	public String status() {
		String s = "Permit type: University Member Permit \n" + super.status() 
				+  " \n Date of issue: #" + lnkDate.getDay();
		return s;
	}
   	
    /**
     * @param d the new issue date
     */
    public void changeDate(Date lnkDate) { this.lnkDate = lnkDate; }
    
    /**
     * @return the issue date
     */
    public Date getIssueDate() { return lnkDate; }
    
   
}
